# -*- mode: python ; coding: utf-8 -*-
# 版本: v3.0.2
import sys
import os

# 从环境变量获取控制台模式设置
console_mode = os.environ.get('AEMEATH_CONSOLE_MODE') == '1'

# 分析阶段
a = Analysis(
    ['main.py'],
    pathex=[],
    binaries=[],
    datas=[
        ('assets', 'assets'),
    ],
    hiddenimports=[
        'PIL._tkinter',
        # asyncio - DashScope SDK需要
        'asyncio',
        'asyncio.events',
        'asyncio.locks',
        'asyncio.queues',
        'asyncio.runners',
        'asyncio.tasks',
        'asyncio.transports',
        'asyncio.protocols',
        'asyncio.base_events',
        'asyncio.futures',
        'asyncio.streams',
        'asyncio.subprocess',
        'asyncio.threads',
        'asyncio.sslproto',
        # asyncio - DashScope SDK需要
        'asyncio',
        'asyncio.events',
        'asyncio.locks',
        'asyncio.queues',
        'asyncio.runners',
        'asyncio.tasks',
        'asyncio.transports',
        'asyncio.protocols',
        'asyncio.base_events',
        'asyncio.futures',
        'asyncio.streams',
        'asyncio.subprocess',
        'asyncio.threads',
        'asyncio.sslproto',
        # 语音交互相关隐式导入
        'nls',  # 阿里云NLS SDK的模块名
        'alibabacloud_nls',  # 包名（以防万一）
        # DashScope SDK - 阿里云百炼官方SDK
        'dashscope',
        'dashscope.__version__',
        'dashscope.api_entities',
        'dashscope.api_entities.dashscope_response',
        'dashscope.audio',
        'dashscope.audio.tts',
        'dashscope.audio.tts_v2',  # TTS语音合成
        'dashscope.audio.asr',  # ASR语音识别
        'dashscope.audio.speech',
        'dashscope.common',
        'dashscope.common.constants',
        'dashscope.common.error',
        'dashscope.common.logging',
        'dashscope.common.protocol',
        'dashscope.common.utils',
        'dashscope.studio',
        'dashscope.client',
        'dashscope.client.api_client',
        'dashscope.client.base_api',
        'dashscope.client.websocket_client',
        # DashScope可能需要的其他模块
        'concurrent',
        'concurrent.futures',
        'concurrent.futures._base',
        'concurrent.futures.thread',
        'websockets',
        'websockets.client',
        'websockets.connection',
        'websockets.datastructures',
        'websockets.exceptions',
        'websockets.extensions',
        'websockets.frames',
        'websockets.headers',
        'websockets.http',
        'websockets.protocol',
        'websockets.server',
        'websockets.streams',
        'websockets.typing',
        'websockets.uri',
        'websockets.utils',
        'websockets.version',
        'dashscope.client',
        'dashscope.client.api_client',
        'dashscope.client.base_api',
        'dashscope.client.websocket_client',
        # DashScope可能需要的其他模块
        'concurrent',
        'concurrent.futures',
        'concurrent.futures._base',
        'concurrent.futures.thread',
        'websockets',
        'websockets.client',
        'websockets.connection',
        'websockets.datastructures',
        'websockets.exceptions',
        'websockets.extensions',
        'websockets.frames',
        'websockets.headers',
        'websockets.http',
        'websockets.protocol',
        'websockets.server',
        'websockets.streams',
        'websockets.typing',
        'websockets.uri',
        'websockets.utils',
        'websockets.version',
        # OpenAI SDK - 用于OpenAI兼容接口
        'openai',
        'openai.__version__',
        'openai.api_resources',
        'openai.api_resources.chat',
        'openai.api_resources.completions',
        'openai.api_resources.models',
        'openai.api_resources.files',
        'openai.api_resources.audio',
        'openai.models',
        'openai.models.chat',
        'openai.models.completions',
        'openai.models.audio',
        'openai.models.models',
        'openai.util',
        'openai.util.utils',
        # pyaudio 依赖
        'portaudio',
        '_portaudio',
        'pyaudio._pyaudio',
        'wave',
        # 音频处理
        'sounddevice',
        'soundfile',
        # AI相关隐式导入
        'zhipuai',
        'requests',
        # 网络相关
        'urllib3',
        'certifi',
        'ssl',
        # JSON处理
        'json',
        'simplejson',
        # WebSocket相关
        'websocket',
        'websocket._abnf',
        'websocket._app',
        'websocket._core',
        'websocket._exceptions',
        'websocket._handshake',
        'websocket._http',
        'websocket._logging',
        'websocket._socket',
        'websocket._ssl_compat',
        'websocket._url',
        'websocket._utils',
        # 其他可能需要的模块
        'charset_normalizer',
        'charset_normalizer.api',
        'charset_normalizer.cd',
        'charset_normalizer.constant',
        'charset_normalizer.legacy',
        'charset_normalizer.models',
        'charset_normalizer.utils',
        'charset_normalizer.version',
        # Tiktoken - OpenAI的token计算库
        'tiktoken',
        'tiktoken.core',
        'tiktoken.registry',
        'tiktoken.model',
        # 阿里云SDK相关模块
        'aliyunsdkcore',
        'aliyunsdkcore.acs_exception',
        'aliyunsdkcore.auth',
        'aliyunsdkcore.auth.credentials',
        'aliyunsdkcore.auth.signers',
        'aliyunsdkcore.client',
        'aliyunsdkcore.http',
        'aliyunsdkcore.profile',
        'aliyunsdkcore.regions',
        'aliyunsdkcore.utils',
        'aliyunsdkcore.vendored',
        'aliyunsdkcore.vendored.requests',
        # 阿里云NLS SDK
        'alibabacloud_nls',
        'alibabacloud_nls.token',
        'alibabacloud_nls.utils',
        # 离线关键词检测
        'sherpa_onnx',
        'sherpa_onnx.keywords',
        'sherpa_onnx.offline',
        'sherpa_onnx.utils',
    ],
    hookspath=[],
    hooksconfig={},
    runtime_hooks=[],
    excludes=['matplotlib', 'test'],
    noarchive=False,
    optimize=0,
)
pyz = PYZ(a.pure)

# 根据控制台模式设置不同的名称
exe_name = 'Aemeath_Console' if console_mode else 'Aemeath'

exe = EXE(
    pyz,
    a.scripts,
    a.binaries,
    a.zipfiles,
    a.datas,
    [],
    name=exe_name,
    debug=False,
    bootloader_ignore_signals=False,
    strip=False,
    upx=True,
    upx_exclude=[],
    runtime_tmpdir=None,
    console=console_mode,
    disable_windowed_traceback=False,
    argv_emulation=False,
    target_arch=None,
    codesign_identity=None,
    entitlements_file=None,
    icon='assets\\gifs\\aemeath.ico',
)